// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:string):Promise<main.ProjectInfo>;

export function GetProjects():Promise<Array<main.ProjectInfo>>;

export function ImportTasks(arg1:string,arg2:string,arg3:string):Promise<main.ImportResult>;

export function IsAuthenticated():Promise<boolean>;

export function IsConfigured():Promise<boolean>;

export function Logout():Promise<void>;

export function NeedsAuth():Promise<boolean>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function StartAuth():Promise<string>;

export function WaitForAuthCode():Promise<void>;
