// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function ImportTasks(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportTasks'](arg1, arg2, arg3);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function NeedsAuth() {
  return window['go']['main']['App']['NeedsAuth']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function StartAuth() {
  return window['go']['main']['App']['StartAuth']();
}

export function WaitForAuthCode() {
  return window['go']['main']['App']['WaitForAuthCode']();
}
